# Generated by Django 5.2 on 2025-05-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
