# Generated by Django 5.2 on 2025-05-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0003_user_bookmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cheer_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
