# Generated by Django 5.2 on 2025-05-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0005_add_initial_candidates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ideology',
        ),
        migrations.AddField(
            model_name='user',
            name='category_score',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ideology_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='top3',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='policy_match',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
