export const CANDIDATE_POLICY = [
  // 이준석
  {
    id: 1,
    title: "정부 부처 통합 및 3부총리제",
    content: "19개 부처 → 13개 부처로 통폐합. \n행정 효율성 극대화",
    main: false,
    prop: ["행정/개혁"],
    candidate: "이준석",
  },
  {
    id: 2,
    title: "국민연금 이원화 개혁",
    content: "신(新)·구(舊) 연금 재정을 분리 \n세대 갈등 완화 및 재정 안정화",
    prop: ["노동자/복지", "경제", "2030"],
    main: true,
    candidate: "이준석",
  },
  {
    id: 3,
    title: "병역의무자 전원 대상 장교 선발제도 도입",
    content:
      "병역의무자 전원을 대상으로 4주간 통합 기초군사훈련을 실시 \n기초군사훈련 성적 우수자를 장교·부사관으로 선발.",
    prop: ["국방", "2030"],
    main: false,
    candidate: "이준석",
  },
  {
    id: 4,
    title: "지자체별 최저임금 자율제",
    content: "최저임금을 지역 여건에 따라 ±30% 내 자율 결정",
    prop: ["ETF/세금", "2030"],
    main: true,
    candidate: "이준석",
  },
  {
    id: 5,
    title: "해외 공장 이전 기업 국내 산업 단지 복귀 지원",
    content:
      "영호남 러스트 벨트 지역 경제 소생 및 제조업 기반 복원 \n* (포항/울산/여수/창원/구미)",
    prop: ["기업친화", "기술", "2030", "4050"],
    main: false,
    candidate: "이준석",
  },
  {
    id: 6,
    title: "법인지방소득세 확대 및 지자체 세율 결정권",
    content: "지방소득세 비중 10% → 30%로 확대. \n각 지자체가 세율 결정",
    prop: ["기업친화", "ETF/세금", "4050"],
    main: false,
    candidate: "이준석",
  },
  {
    id: 7,
    title: "교권 및 수업권 보호",
    content: "무고죄 처벌 강화, 교사 소송 국가 책임제 도입 및 전담 변호사 배치",
    prop: ["교육", "2030", "4050"],
    main: false,
    candidate: "이준석",
  },
  {
    id: 8,
    title: "고졸 이하 청년 대상 '든든출발자금' 지원",
    content:
      "고졸 이하 청년 대상 (만 19~34세) \n연 1.7% 금리로 분기 당 500만원씩 총 10회 지원",
    prop: ["노동자/복지", "2030"],
    main: false,
    candidate: "이준석",
  },
  // 이재명
  {
    id: 9,
    title: "AI 투자 100조원(정부+민간)",
    content: "AI 국가 인재 양성 및 투자로 AI 세계 3대 강국 진입",
    prop: ["기술", "기업친화", "2030"],
    main: true,
    candidate: "이재명",
  },
  {
    id: 10,
    title: "6개 분야에 대해 글로벌 기업 육성",
    content:
      "AI, 바이오/헬스스, 콘텐츠/문화, 방위/우주, 에너지, 제조업 분야 기업 육성",
    prop: ["기술", "기업친화", "2030", "4050"],
    main: false,
    candidate: "이재명",
  },
  {
    id: 11,
    title: "개미투자자 보호 장치 강화",
    content: "상법 개정을 통한 개미투자자 보호 장치 강화",
    prop: ["ETF/세금", "노동자/복지", "2030"],
    main: false,
    candidate: "이재명",
  },
  {
    id: 12,
    title: "정년 연장 추진 및 연금 확대",
    content: "정년 연장 추진 및 노후 소득 위한 '맞춤형 주택 연금' 확대",
    prop: ["행정", "노동자/복지", "4050"],
    main: false,
    candidate: "이재명",
  },
  {
    id: 13,
    title: "상속세 부담 완화 및 실직 소득 상승",
    content:
      "중산층 위한 상속세 부담 완화 \n 직장인 실직 소득 상승을 위한 근로소득세제 합리화",
    prop: ["노동자/복지", "ETF/세금", "2030", "4050"],
    main: false,
    candidate: "이재명",
  },
  {
    id: 14,
    title: "맞춤형 공공 분양/고품질 공공임대 공급 확대",
    content:
      "재개발/재건축 규제 합리화 \n 맞춤형 공공분양, 고품질 공공앰대 공급 확대",
    prop: ["주택", "행정/개혁", "2030"],
    main: false,
    candidate: "이재명",
  },
  {
    id: 15,
    title: "임플란트 보험 확대",
    content: "적용 연령 낮추고 개수 늘림",
    prop: ["노동자/복지", "60+"],
    main: false,
    candidate: "이재명",
  },
  {
    id: 16,
    title: "스마트농업 전국 확산",
    content: "로봇·AI 기술 도입으로 농업 자동화",
    prop: ["기술", "지역균형", "노동자/복지"],
    main: false,
    candidate: "이재명",
  },
  {
    id: 17,
    title: "농업인 노후 보장",
    content:
      "농업인 퇴진 역금제 도입 \n 농지이용 집적화 및 공공 비축 농지 확대 ",
    prop: ["노동자/복지", "4050", "60+"],
    main: false,
    candidate: "이재명",
  },
  {
    id: 18,
    title: "주 4.5일제 도입 기업 지원",
    content: "주 4,5일제를 도입하는 기업에 대해 \n지원을 통해 실노동시간 단축",
    prop: ["노동자/복지", "행정/개혁", "2030"],
    main: true,
    candidate: "이재명",
  },
  {
    id: 19,
    title: "연차휴가 요건 완화 및 이월제 도입",
    content: "휴가 사용 요건 완화 \n3년간 이월 가능한 연차휴가 저축 제도 도입",
    prop: ["노동자/복지", "행정/개혁", "2030"],
    main: false,
    candidate: "이재명",
  },
  {
    id: 20,
    title: "통신비 세액공제 신설 검토",
    content: "가계 통신비도 세제 혜택 검토",
    prop: ["경제", "행정/개혁", "4050"],
    main: false,
    candidate: "이재명",
  },
  // {
  //   id: 21,
  //   title: "초등 예체능비 세액공제",
  //   content: "태권도·미술 등 교육비 공제 대상 확대",
  //   prop: ["교육", "청소년", "2030", "4050"],
  //   main: false,
  //   candidate: "이재명",
  // },
  {
    id: 22,
    title: "반도체 특별법 제정",
    content: "기업이 반도체 개발에 \n주력할 수 있도록 특별법 신설",
    prop: ["기술", "기업친화", "4050"],
    main: false,
    candidate: "이재명",
  },
  {
    id: 23,
    title: "반도체 생산세액공제 확대",
    content: "국내 생산 반도체 세액공제 최대 10%",
    prop: ["기술", "기업친화", "4050"],
    main: false,
    candidate: "이재명",
  },
  {
    id: 24,
    title: "공공의대 설립",
    content: "지역 의료 인력 양성 위한 국립의대 설립",
    prop: ["노동자/복지", "교육", "2030"],
    main: false,
    candidate: "이재명",
  },
  {
    id: 25,
    title: "국가가 국민 먹거리 책임",
    content:
      "대학생/노동자에게 '천원 아침밥' 제공 \n 임산부 친환경 논산물꾸러미 및 초등생 과일 간식 사업 재개",
    prop: ["노동자/복자", "2030"],
    main: false,
    candidate: "이재명",
  },
  {
    id: 26,
    title: "전라선 고속철도 추진",
    content: "호남권 수도권 접근성 개선 철도 구축",
    prop: ["행정/개혁", "국방", "2030"],
    main: false,
    candidate: "이재명",
  },
  {
    id: 38,
    title: "가상자산 시장 제도화",
    content: "가상자산 현물 ETF 허용 \n 디지털자산육성기본법 제정",
    prop: ["행정/개혁", "2030", "4050"],
    main: false,
    candidate: "이재명",
  },
  // 김문수
  {
    id: 27,
    title: "GTX 전국 확대",
    content:
      "지방주도 균형발전을 위한 권역별 GTX 건설 \n 충청/전남/경남/경북권 GTX 신설",
    prop: ["교통", "지역균형", "2030", "4050"],
    main: true,
    candidate: "김문수",
  },
  {
    id: 28,
    title: "일자리 창출 기업 집중 지원",
    content:
      "일자리 창출 기업데 대해 세금/이자/부담금 감면 \n 토지/교통/용수/기술/세금 등 기업 투자 원스톱 지원",
    prop: ["기업친화", "행정/개혁", "ETF/세금", "4050"],
    main: false,
    candidate: "김문수",
  },
  {
    id: 29,
    title: "법인세•상속세 인하",
    content: "법인세 최고 세율 24% → 21% \n 상속세 50% → 30%",
    prop: ["기업친화", "ETF/세금", "4050"],
    main: true,
    candidate: "김문수",
  },
  {
    id: 30,
    title: "대통령실 내 '기업 민원 수석' 신설",
    content: "기업 민원 수석 통해 기업인의 애로사항 청취",
    prop: ["4050", "기업친화"],
    main: false,
    candidate: "김문수",
  },
  {
    id: 31,
    title: "10대 신기술 적극 지원",
    content:
      "10대 신기술(인공지능/반도체/이차전지/바이오/ \n모빌리티/양자/로봇/우주항공/탄소중립/사어버보안)에 대해 \n국가 산업 육성 트랙 반영",
    prop: ["기술", "2030", "4050", "기업친화"],
    main: false,
    candidate: "김문수",
  },
  {
    id: 32,
    title: "기업 별 자율 정년 연장",
    content:
      "기업 별 자율에 의한 정년 연장에는 동의, \n 모든 직무(산업)에 적용되는 일률적인 정년 연장에 대해서는 반대",
    prop: ["노동자/복지", "기업친화", "2030", "4050"],
    main: false,
    candidate: "김문수",
  },
  {
    id: 33,
    title: "노사간 합의로 '노동시간' 결정",
    content:
      "지나친 노동 시간 규제 반대. \n 예) R&D, 게임 산업에선 개발하는 도중 8시간이 돼서 집에 가는 건 비합리적.",
    prop: ["노동자/복지", "기업친화", "2030"],
    main: false,
    candidate: "김문수",
  },
  {
    id: 34,
    title: "고령층 버스 무임 확대",
    content: "65세 이상에 한해 오전 9시~오후 5시 고령층 버스 무료 이용",
    prop: ["교통", "노동자/복지", "60+"],
    main: false,
    candidate: "김문수",
  },
  {
    id: 35,
    title: "1인가구 맞춤형 공공주택 공급 확대",
    content:
      "공공주택 내 의료•돌봄 시설 의무화 \n 1인 가구 맞춤형 주택 공급 확대",
    prop: ["주택", "노동자/복지", "2030"],
    main: false,
    candidate: "김문수",
  },
  {
    id: 36,
    title: "핵추진 잠수함•핵연료 재처리 기술 확보",
    content:
      "당선 즉시 한미 정상회담 추진을 통해 \n핵추진 잠수함/핵연료 재처리 기술 확보 \n 미국 중심 외교 전략 고수",
    prop: ["국방", "기술"],
    main: false,
    candidate: "김문수",
  },
  {
    id: 37,
    title: "서해 구조물 불법 설치 단호 대응",
    content: "서해 구조물 불법 설치 등 \n중국과 마찰 시 단호하게 대응",
    prop: ["국방"],
    main: false,
    candidate: "김문수",
  },
  {
    id: 38,
    title: "가상자산 시장 제도화",
    content: "가상자산 현물 ETF 허용 \n 디지털자산육성기본법 제정",
    prop: ["ETF/세금", "2030", "4050"],
    main: false,
    candidate: "김문수",
  },
  {
    id: 39,
    title: "원전 중심 에너지 전환",
    content:
      "원자력 비중 32.5% → 60% 확대 \n 석탄 발전 비중 29.4% → 0% \n 소형모듈원전(SMR) 상용화 추진",
    prop: ["국방"],
    main: false,
    candidate: "김문수",
  },
  {
    id: 40,
    title: "종합소득세에 물가 연동제 도입",
    content:
      "종합 소득세에 물가 연동제 도입하여 중산층 감세 추진 \n ISA 세제 지원 확대",
    prop: ["ETF/세금"],
    main: false,
    candidate: "김문수",
  },
  {
    id: 41,
    title: "국회의원 불체포 특권 폐지",
    content: "국회의원 불체포 특권 및 공수처 폐지 \n 선관위 감사원 감사 허용",
    prop: ["행정/개혁"],
    main: false,
    candidate: "김문수",
  },
  {
    id: 42,
    title: "대학가 및 산업 단지 근처 '반값 월세존' 구축",
    content: "대학가, 산단 인근 월세 인하 구역 설정",
    prop: ["주택", "2030"],
    main: false,
    candidate: "김문수",
  },
  {
    id: 43,
    title: "3•3•3 청년 주택 공급 방안",
    content:
      "결혼하면 3년, 첫 아이 3년, 둘째 아이 3년. \n 최대 9년 주거비 지원",
    prop: ["주택", "2030"],
    main: false,
    candidate: "김문수",
  },
];

export default CANDIDATE_POLICY;
